version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME:-bylw2-mysql}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-example}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-lw_survey}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-example}
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password", "--sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"]

  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
