// 问卷和调查相关的假数据
export const mockCategories = [
  { id: 1, name: "心理健康", slug: "psychology", count: 18, description: "评估心理状态，提供心理调节建议" },
  { id: 2, name: "学习能力", slug: "learning", count: 15, description: "测试学习方法，提升学习效率" },
  { id: 3, name: "职业发展", slug: "career", count: 12, description: "职业规划指导，发现职业潜能" },
  { id: 4, name: "生活方式", slug: "lifestyle", count: 14, description: "健康生活评估，改善生活质量" },
  { id: 5, name: "兴趣爱好", slug: "hobbies", count: 9, description: "发现兴趣偏好，丰富业余生活" },
  { id: 6, name: "人际关系", slug: "social", count: 11, description: "改善人际交往，建立良好关系" },
  { id: 7, name: "情绪管理", slug: "emotion", count: 13, description: "情绪调节技巧，提升情商水平" },
  { id: 8, name: "认知能力", slug: "cognitive", count: 10, description: "认知功能测试，训练思维能力" }
];

export const mockSurveys = [
  {
    id: 1,
    title: "心理健康评估问卷",
    description: "评估您当前的心理健康状况，提供个性化建议和心理调节方案",
    category: "心理健康",
    categoryId: 1,
    author: "李心理",
    authorId: 3,
    questions: 15,
    duration: 10,
    difficulty: "中等",
    status: "published",
    tags: ["心理", "健康", "评估", "情绪管理"],
    thumbnail: "/images/psychology.jpg",
    rating: 4.5,
    participants: 1250,
    participantCount: 1250,
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z"
  },
  {
    id: 2,
    title: "学习方式偏好调查",
    description: "了解您的学习偏好，帮助您找到最适合的学习方法和提升效率",
    category: "学习能力",
    categoryId: 2,
    author: "王教授",
    authorId: 4,
    questions: 20,
    duration: 15,
    difficulty: "简单",
    status: "published",
    tags: ["学习", "方法", "偏好", "效率"],
    thumbnail: "/images/learning.jpg",
    rating: 4.2,
    participants: 890,
    participantCount: 890,
    createdAt: "2024-01-08T09:00:00Z",
    updatedAt: "2024-01-12T14:20:00Z"
  },
  {
    id: 3,
    title: "职业兴趣测试",
    description: "发现您的职业兴趣和潜在发展方向，为职业规划提供科学依据",
    category: "职业发展",
    categoryId: 3,
    author: "张规划师",
    authorId: 5,
    questions: 25,
    duration: 20,
    difficulty: "中等",
    status: "published",
    tags: ["职业", "兴趣", "规划", "发展"],
    thumbnail: "/images/career.jpg",
    rating: 4.7,
    participants: 2150,
    participantCount: 2150,
    createdAt: "2024-01-05T11:00:00Z",
    updatedAt: "2024-01-18T16:45:00Z"
  },
  {
    id: 4,
    title: "压力管理能力测试",
    description: "评估您面对压力时的应对能力，学习有效的压力管理技巧",
    category: "情绪管理",
    categoryId: 7,
    author: "陈医师",
    authorId: 6,
    questions: 18,
    duration: 12,
    difficulty: "中等",
    status: "published",
    tags: ["压力", "管理", "应对", "心理"],
    thumbnail: "/images/stress.jpg",
    rating: 4.3,
    participants: 1680,
    participantCount: 1680,
    createdAt: "2024-01-12T10:00:00Z",
    updatedAt: "2024-01-20T09:15:00Z"
  },
  {
    id: 5,
    title: "记忆力水平测试",
    description: "科学测试您的记忆力水平，提供针对性的记忆提升建议",
    category: "认知能力",
    categoryId: 8,
    author: "刘博士",
    authorId: 7,
    questions: 22,
    duration: 18,
    difficulty: "困难",
    status: "published",
    tags: ["记忆力", "测试", "认知", "提升"],
    thumbnail: "/images/memory.jpg",
    rating: 4.6,
    participants: 756,
    participantCount: 756,
    createdAt: "2024-01-14T14:30:00Z",
    updatedAt: "2024-01-22T11:20:00Z"
  },
  {
    id: 6,
    title: "领导力风格评估",
    description: "评估您的领导力风格，了解自己的管理特点和改进方向",
    category: "职业发展",
    categoryId: 3,
    author: "马经理",
    authorId: 8,
    questions: 30,
    duration: 25,
    difficulty: "中等",
    status: "published",
    tags: ["领导力", "管理", "风格", "评估"],
    thumbnail: "/images/leadership.jpg",
    rating: 4.4,
    participants: 1320,
    participantCount: 1320,
    createdAt: "2024-01-16T16:00:00Z",
    updatedAt: "2024-01-24T13:45:00Z"
  },
  {
    id: 7,
    title: "健康生活方式评估",
    description: "评估您的生活方式是否健康，提供个性化的健康改善建议",
    category: "生活方式",
    categoryId: 4,
    author: "赵营养师",
    authorId: 9,
    questions: 16,
    duration: 8,
    difficulty: "简单",
    status: "published",
    tags: ["健康", "生活方式", "营养", "运动"],
    thumbnail: "/images/health.jpg",
    rating: 4.1,
    participants: 2340,
    participantCount: 2340,
    createdAt: "2024-01-18T08:30:00Z",
    updatedAt: "2024-01-26T10:10:00Z"
  },
  {
    id: 8,
    title: "人际交往能力测试",
    description: "测试您的人际交往能力，帮助您建立更好的人际关系",
    category: "人际关系",
    categoryId: 6,
    author: "吴心理师",
    authorId: 10,
    questions: 24,
    duration: 15,
    difficulty: "中等",
    status: "published",
    tags: ["人际关系", "交往", "社交", "沟通"],
    thumbnail: "/images/social.jpg",
    rating: 4.2,
    participants: 987,
    participantCount: 987,
    createdAt: "2024-01-20T12:00:00Z",
    updatedAt: "2024-01-28T15:30:00Z"
  },
  {
    id: 9,
    title: "创新思维能力评估",
    description: "评估您的创新思维能力，发现创意潜能并提供思维训练建议",
    category: "认知能力",
    categoryId: 8,
    author: "郑创新师",
    authorId: 11,
    questions: 19,
    duration: 14,
    difficulty: "困难",
    status: "published",
    tags: ["创新", "思维", "创意", "训练"],
    thumbnail: "/images/innovation.jpg",
    rating: 4.5,
    participants: 623,
    participantCount: 623,
    createdAt: "2024-01-22T09:45:00Z",
    updatedAt: "2024-01-29T14:20:00Z"
  },
  {
    id: 10,
    title: "时间管理效率测试",
    description: "评估您的时间管理能力，学习高效的时间安排和任务规划方法",
    category: "职业发展",
    categoryId: 3,
    author: "黄效率专家",
    authorId: 12,
    questions: 21,
    duration: 16,
    difficulty: "中等",
    status: "published",
    tags: ["时间管理", "效率", "规划", "生产力"],
    thumbnail: "/images/time.jpg",
    rating: 4.3,
    participants: 1456,
    participantCount: 1456,
    createdAt: "2024-01-24T11:15:00Z",
    updatedAt: "2024-01-30T16:40:00Z"
  },
  {
    id: 11,
    title: "运动习惯与健康调查",
    description: "了解您的运动习惯，制定适合的健身计划和健康生活指导",
    category: "生活方式",
    categoryId: 4,
    author: "林健身教练",
    authorId: 13,
    questions: 14,
    duration: 10,
    difficulty: "简单",
    status: "published",
    tags: ["运动", "健身", "习惯", "健康"],
    thumbnail: "/images/fitness.jpg",
    rating: 4.0,
    participants: 1890,
    participantCount: 1890,
    createdAt: "2024-01-26T07:30:00Z",
    updatedAt: "2024-02-01T12:00:00Z"
  },
  {
    id: 12,
    title: "音乐偏好与性格分析",
    description: "通过您的音乐偏好分析性格特点，探索音乐与心理的奇妙联系",
    category: "兴趣爱好",
    categoryId: 5,
    author: "周音乐治疗师",
    authorId: 14,
    questions: 17,
    duration: 12,
    difficulty: "简单",
    status: "published",
    tags: ["音乐", "性格", "偏好", "分析"],
    thumbnail: "/images/music.jpg",
    rating: 4.4,
    participants: 1234,
    participantCount: 1234,
    createdAt: "2024-01-28T13:20:00Z",
    updatedAt: "2024-02-03T09:50:00Z"
  }
];

export const mockSurveyDetail = {
  id: 1,
  title: "心理健康评估问卷",
  description: "评估您当前的心理健康状况，提供个性化建议",
  category: "心理健康",
  categoryId: 1,
  author: "心理学专家",
  authorId: 3,
  questions: [
    {
      id: 1,
      type: "single",
      title: "您最近一周的睡眠质量如何？",
      options: [
        { id: "a", text: "很好，每天都能充足睡眠" },
        { id: "b", text: "一般，偶尔失眠" },
        { id: "c", text: "较差，经常失眠" },
        { id: "d", text: "很差，严重失眠" }
      ],
      required: true
    },
    {
      id: 2,
      type: "single",
      title: "您对目前的生活状态满意吗？",
      options: [
        { id: "a", text: "非常满意" },
        { id: "b", text: "比较满意" },
        { id: "c", text: "一般" },
        { id: "d", text: "不太满意" },
        { id: "e", text: "很不满意" }
      ],
      required: true
    },
    {
      id: 3,
      type: "multiple",
      title: "您在日常生活中会遇到以下哪些情况？（可多选）",
      options: [
        { id: "a", text: "感到焦虑或紧张" },
        { id: "b", text: "情绪低落" },
        { id: "c", text: "注意力难以集中" },
        { id: "d", text: "社交恐惧" },
        { id: "e", text: "以上都没有" }
      ],
      required: false
    }
  ],
  duration: 10,
  difficulty: "中等",
  status: "published",
  tags: ["心理", "健康", "评估"],
  thumbnail: "/images/psychology.jpg",
  rating: 4.5,
  participants: 1250,
  isFavorite: false,
  createdAt: "2024-01-10T08:00:00Z",
  updatedAt: "2024-01-15T10:30:00Z"
};

export const mockComments = [
  {
    id: 1,
    surveyId: 1,
    userId: 1,
    username: "张三",
    avatar: "/avatars/user1.jpg",
    content: "这个问卷很有帮助，让我更了解自己的心理状况。",
    rating: 5,
    createdAt: "2024-01-16T10:30:00Z"
  },
  {
    id: 2,
    surveyId: 1,
    userId: 2,
    username: "李四",
    avatar: "/avatars/user2.jpg",
    content: "题目设计得很专业，结果分析也很详细。",
    rating: 4,
    createdAt: "2024-01-17T14:20:00Z"
  }
];

export const mockQuestionnaires = [
  {
    id: 1,
    title: "员工满意度调查",
    description: "了解员工对公司各方面的满意度",
    creator: "HR部门",
    creatorId: 3,
    status: "active",
    questions: 12,
    responses: 45,
    createdAt: "2024-01-12T09:00:00Z"
  },
  {
    id: 2,
    title: "产品用户体验调研",
    description: "收集用户对产品的使用体验和改进建议",
    creator: "产品经理",
    creatorId: 3,
    status: "draft",
    questions: 18,
    responses: 0,
    createdAt: "2024-01-18T11:30:00Z"
  }
];

export const mockSubmitResponse = {
  success: true,
  message: "问卷提交成功",
  data: {
    answerId: 123,
    score: 85,
    result: "良好",
    analysis: "您的心理健康状况整体良好，建议保持目前的生活方式。"
  }
};